version: "3.8"
services:
  app:
    image: devops-FinalProject:latest
    ports:
      - "5000:5000"
    services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
