pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo "Build stage completed"
            }
        }

        stage('SonarQube Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    bat '''
                    sonar-scanner ^
                    -Dsonar.projectKey=devops-finalproject ^
                    -Dsonar.sources=app ^
                    -Dsonar.host.url=http://localhost:9000 ^
                    -Dsonar.login=%SONAR_TOKEN%
                    '''
                }
            }
            
stage('Quality Gate') {
    steps {
        timeout(time: 2, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: true
        }
    }
}

        }

       stage('Docker Build') {
    steps {
        bat '''
        export DOCKER_BUILDKIT=0
        docker build -t devops-finalproject/app:latest -f docker/Dockerfile .
        '''
    }
   }
 }

    post {
        success {
            echo "✅ Pipeline completed successfully"
        }
        failure {
            echo "❌ Pipeline failed – check logs"
        }
    }
}