pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo "Build stage completed"
            }
        }

        stage('SonarQube Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    bat '''
                    sonar-scanner ^
                    -Dsonar.projectKey=devops-finalproject ^
                    -Dsonar.sources=app ^
                    -Dsonar.host.url=http://localhost:9000 ^
                    -Dsonar.login=%SONAR_TOKEN%
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t devops-finalproject/app -f docker/Dockerfile .'
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully"
        }
        failure {
            echo "❌ Pipeline failed – check logs"
        }
    }
}